[package]
name = "spaceifier-app"
version = "0.1.0"
authors = ["ZigTag"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spaceifier = { path = "./spaceifier" }
iced = "0.1"
clipboard = "0.5"
