name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Spaceifier crate test
      run: |
          cd spaceifier
          cargo test
    - name: Spaceifier-app compile
      run: cargo build
          
          
          
